# Generated by Django 6.0 on 2025-12-18 09:46

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('expense', 'Expense'), ('income', 'Income')], max_length=10)),
                ('name', models.CharField(max_length=60)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='finance.category')),
            ],
        ),
        migrations.CreateModel(
            name='FxRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('rate', models.DecimalField(decimal_places=8, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('1E-8'))])),
                ('base', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fx_base_rates', to='finance.currency')),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fx_quote_rates', to='finance.currency')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('expense', 'Expense'), ('income', 'Income')], max_length=10)),
                ('occurred_at', models.DateTimeField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('fx_rate', models.DecimalField(decimal_places=8, default=Decimal('1.0'), max_digits=18)),
                ('base_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('merchant', models.CharField(blank=True, default='', max_length=120)),
                ('note', models.TextField(blank=True, default='')),
                ('receipt_url', models.URLField(blank=True, default='')),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='finance.category')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='finance.currency')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='finance.wallet')),
            ],
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['owner', 'type'], name='finance_cat_owner_i_b8e85d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('owner', 'type', 'name')},
        ),
        migrations.AddIndex(
            model_name='fxrate',
            index=models.Index(fields=['date', 'base', 'quote'], name='finance_fxr_date_3f45d9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='fxrate',
            unique_together={('date', 'base', 'quote')},
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['owner', 'occurred_at'], name='finance_tra_owner_i_a7bcee_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['owner', 'type'], name='finance_tra_owner_i_903a4e_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['owner', 'is_deleted'], name='finance_tra_owner_i_24824b_idx'),
        ),
    ]
