# Generated by Django 6.0 on 2025-12-18 09:58

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_category_fxrate_transaction_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=7)),
                ('scope', models.CharField(choices=[('total', 'Total'), ('category', 'Category')], default='total', max_length=10)),
                ('limit_base_amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('alert_80_sent', models.BooleanField(default=False)),
                ('alert_100_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.category')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['owner', 'month'], name='finance_bud_owner_i_c31bbd_idx'), models.Index(fields=['owner', 'month', 'scope'], name='finance_bud_owner_i_a0383a_idx')],
                'unique_together': {('owner', 'month', 'scope', 'category')},
            },
        ),
    ]
