# Generated by Django 6.0 on 2025-12-18 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_budget'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('expense', 'Expense'), ('income', 'Income'), ('transfer_out', 'Transfer Out'), ('transfer_in', 'Transfer In')], max_length=20),
        ),
        migrations.CreateModel(
            name='TransferLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('in_tx', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_in_link', to='finance.transaction')),
                ('out_tx', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_out_link', to='finance.transaction')),
            ],
        ),
    ]
