# Generated by Django 6.0 on 2025-12-18 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_alter_transaction_type_transferlink'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='receipt_file',
            field=models.ImageField(blank=True, null=True, upload_to='receipts/%Y/%m/'),
        ),
    ]
