# Generated by Django 6.0 on 2025-12-19 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_aiinsight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='receipt_url',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
